In [1]:
import numpy as np

In [12]:
arr = np.identity(3)

In [8]:
np.sum([[1, 2, 3]])

6

In [10]:
np.dot([[1, 2, 3]], [[1, 1, 1], [0, 0, 0], [0, 0, 0]])

array([[1, 1, 1]])

In [13]:
arr == 1

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [14]:
np.sum(arr)

3.0

In [16]:
np.matmul([[1, 1, 1]], [[1, 2, 3]])

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

In [17]:
a = np.array([1, 2, 3])

In [18]:
a - a

array([0, 0, 0])

In [19]:
a + 2

array([3, 4, 5])

In [20]:
a**2

array([1, 4, 9])

In [21]:
a <=2

array([ True,  True, False])

In [22]:
a.shape[0]

3

In [23]:
a.sum

<function ndarray.sum>

In [24]:
a.sum()

6

In [25]:
a = np.array([[1, 1, 3, 2, 4]])

In [26]:
a = a.T

In [27]:
a

array([[1],
       [1],
       [3],
       [2],
       [4]])

In [28]:
a[:-1] += 1

In [29]:
a

array([[2],
       [2],
       [4],
       [3],
       [4]])